// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// import 'firebase_options.dart';
// ...
//  await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARl7uPQhALShMSLADuoutJQ7uyEMGoQnc',
    appId: '1:726679404126:web:4437031c28b0e5633bbecf',
    messagingSenderId: '726679404126',
    projectId: 'app-project-d3cb6',
    authDomain: 'app-project-d3cb6.firebaseapp.com',
    storageBucket: 'app-project-d3cb6.firebasestorage.app',
    measurementId: 'G-8LRL0VEQJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGVtpyGpPcAYz2_dCYBSlAD8iASKCL3uM',
    appId: '1:726679404126:android:819895a6dc459d623bbecf',
    messagingSenderId: '726679404126',
    projectId: 'app-project-d3cb6',
    storageBucket: 'app-project-d3cb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD63n44mnRdGDGDgB1FYl9aGg1Obn6rD5w',
    appId: '1:726679404126:ios:69ec0900467fbd083bbecf',
    messagingSenderId: '726679404126',
    projectId: 'app-project-d3cb6',
    storageBucket: 'app-project-d3cb6.firebasestorage.app',
    iosBundleId: 'com.example.appProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARl7uPQhALShMSLADuoutJQ7uyEMGoQnc',
    appId: '1:726679404126:web:799d61d5fa2e8b9b3bbecf',
    messagingSenderId: '726679404126',
    projectId: 'app-project-d3cb6',
    authDomain: 'app-project-d3cb6.firebaseapp.com',
    storageBucket: 'app-project-d3cb6.firebasestorage.app',
    measurementId: 'G-3QM8NWP1FV',
  );
}
